
[[prereg_algs]]
=== Required Prerequisite Algorithms for X-WING Validations

X-WING relies on underlying cryptographic primitives as defined by the X-WING specifications.  Each prerequisite algorithm required for X-WING validation *MUST* be validated either separately or as part of the same submission.  ACVP provides the prereqVals mechanism for specifying the applicable prerequisite algorithm validation.

The implementation relies on the following underlying algorithms:

   * ML-KEM-768: Conforming to FIPS 203 <<FIPS203>> (Module-Lattice-Based Key Encapsulation mechanism)
   * X25519: Conforming to SP 800-186 / RFC7748 for elliptic-curve cryptography<<RFC7748>>.   
   * X25519:as specified in <<RFC7748>>, is a required prerequisite algorithm for X-WING validation.

[[rereqs_table]]
.Required X-WING Prerequisite Algorithms JSON Values
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm
| A prerequisite algorithm
| string
| SHA, ML-KEM, or X25519

| valValue
| Algorithm validation number
| string
| Actual numbr or "same"

| prereqAlgVal
| Prerequisite algorithm validation
| Object with algorith and valValue properties
| See above
|===

=== X-WING Algorithm Registration Properties

Each X-WING algorithm capability advertised is a self-contained JSON object using the following values.
[[X-WING_caps_table]]
.X-WING Algorithm Capabilities JSON Values
|===
| JSON Value | Description | JSON Type | Valid Values
| algorithm | Algorithm Validation | string | X-WING
| mode | X-WING mode to be validated| string | keyGen, encapDecap                             
| revision | The algorithm testing revision to be used | string | See <<supported>>
|prereqVals | Prerequisite algorithm validation | array | See <<prerequisites>>
| function | The X-WING operation supported by the IUT | array | encapsulation, decapsulation
|===

Note: The function property is applicable only to X-WING/ encapDecap registration.

