[[X-WING_keygen_test_Vectors]]
== X-WING Key Generation Test Vectors

[[X-WING_keygen_tgjs_2]]
== X-WING Key Generation Test Groups JSON Schema Intro

The Key Generation test vectors verify the implementation correctly performs the X-WING GenerateKeyPair() operation.  THe server supplies the deterministic 32-byte SkSeed (seed).  The implementation under test (IUT) shall generate the corresponding X-WING public (encapsulation)
 key 9pk) and decapsulation key (dk).

These tests verify the implementation of the x-WING GenerateKeyPair() procedure defined om Section 5.2 of <<XWING>>.

== Prompt JSON

[source, json]
----
{
   "tgId": 1,
    "tests": [
      {
         "tcId": 1,
         "seed": "0123456789ABCDEF..."
       }
    ]
}
----

|===

| Property | Description

| seed
| Deterministic seed used to generate the X-WING key pair.

| tcId
| Test case Identifier.

|===

== Expected Results



[source, json]
----
{
   "tgId": 1,
   "tests": [
     {
       "tcId": 1,
       "pk": "A1B2C3D4...",
       "dk": "E5F60718..."
     }
   ]
}
----
|===
| Property | Description

| pk
| X-WING public (encapsulation) key.

| dk
| X-WING decapsulation key.

| tcId
| test case identifier.

|===

