[[X-WING_encapDecap_test_vectors]]
=== X-WING encapDecap Test Vectors

[[X-WING_encapDecap_tgjs]]
==== X-WING encapDecap Test Groups JSON Schema

he testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. The Test Group JSON object contains metadata that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for X-WING / encapDecap / 1.0 is as follows:

[[X-WING_keyGen_vs_tg_table]]
X-WING keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON Type

| tgId
| Numeric identifier for the test group, unique across the entire vector set
| integer

| testType
| The test operation performed
| string

| tests
|Array of individual test vector JSON objects, which are defined in <<X-WING_encapDecap_tvjs>>
| array
|===

[[X-WING_encapDecap_tvjs]]
==== X-WING encapDecap Test Case JSON Schema

each test group contains an array of ne or more tst caes.  Each test case is a JSON object that represents a single test vector to be processed by the CVP client.  the following table describes the JSON elements for ech X-WING test vector.

[[X-WING_encapDecap_vs_tc_table]]
X-WING keyGen test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcID
| Numeric identifier for the tst case, unique across the entire vector set
| integer

| pk
| The 1216-byte encapsulation key when the function is encapsulation.
| hex

| eseed
| 64-byte deterministic encapsulation seed when the function is encalsulation
| hex

| sk
| The 32-byte dcapsulation key when th function is decapsulation
| hex

| ct
| the 1120-byte ciphertext when the function is decapsulation
| hex
|===

The following is an example JSON object sent from the server to the client for X-WING/ encapDecap / 1.0

.Prompt JSON
[source,json]
----
[
 {
   "acvVersion": "<acvp-version>"
  },
  {
    "vsId": 0,
     "algorithm": "X-WING",
     "mode" : "encapDecap",
     "revision": "1.0",
     "testGroups": [
    {
       "tgId": 1,
       "testTypes": "AFT",
       "function": "encapsulation",
        "tests": [
      {
         "tcId": 1,
         "pk": "0123456789ABCDEF...",
         "eseed": "01A12B34C..."
       }
     ]
    }
   ]
  }
]
----

