
[[X-WING_keygen_tgjs]]
== X-WING Key Generation Responses

The X-Wing Key Generation response object contains the key pair generated by the implementation under test (IUT).  The response in returned to the ACVP server for validation following successful execution of the X-WING GenerateKeyPair() operation.

.X-WING Top-Level Response JSON Object
|===
| Property | Description

| acvVersion
| Version of the ACVP protocol.

| vsId
| Vector set identifier assigned by the ACVP server.

| testGroups
| Array of X-WING test groups.

|===

.Test Groups
|===
| Property | Description

| tgId
| Test group identifier.

| tests
| Array of response test cases.
|===

=== Test Cases

For ech key generation test case, the IUT shall generate the corresponding X-WING public (encapsulation) key (pk) and decapsulation key (dk) from the supplied deterministic seed.

.Property Table
|===
| Property | Description

| tcId
| Test case identifier.

| pk
| X-WING public (encapsulation) key generated by the 'GenerateKeyPair()' operation.

| dk
| X-WING decapsulation key generated by the 'generateKeyPair()' operation.
|===

.Example JSON Test Vector Response
[source.json]
----
[
  {
    "acvVersion': <acvp-version>
   },
  {
   "vsId": 0,
   "testGroups": [
      {
        "tgId": 1,
         "tests": [
            {
               "tcId": 1,
               "pk": "A1B2C3D4",
               "dk": "E1F2G3h4"
            }
         ]
        }
      ]
   }
]
----
