[[X-WING_encapDecap_vector_responses]]
== X-WING encapDecap Test Vector Responses

The X-WING EncapDecap responses object contains the results generated by the implementation under test (IUT) after processing the supplied test vectors.  Response objects contain the values computed by the IUT and are returned to the ACVP server for validation.

=== Top-Level Response Object
|===
| Property | Description

| acvVersion
| Version of the ACVP protocol

| vsId
| Vector set identifier assigned by the ACVP server.

| testGroups
| Array of X-wing test Groups.
|===

=== Test Groups
|===
| Property | Description

| tgid 
| Test group identifier.

| tests
| Array of response test cases.
|===

=== Encapsulation Response

For encapsulation, the IUT shall return the generated ciphertxt (ct) and shared secret (ss).

=== Property Table
|===
| Property | Description

| tcId
| Test case identifier.

| ct
| X-WING ciphertext generated by the encapsulation operation.
|===

=== Example
[source, json]
----
  {
   "tcId": 17,
   "ct": "F4AE2B7C...",
   "ss": "C57A25...",   
  }
   
----

=== Decapsulation Response

For decapsulation, the IUT shall return the shared secret (ss) derived from the supplied decapsulation key 9dk0 and cipheretext (ct).

=== Property Table

|===
| Property | Description

| tcId
| Test case identifier

| ss
| Shared secret generated by the decapsulation operation.

|===

=== Example
[source, json]
----
  {
   "tcId": 26  
   "ss": "1D1AE...",   
  }
   
----

=== Validation Response

Validation respose contains the shared secret (ss) produced after processing both valid and modified ciphertexts. Modified ciphertext test cases independently exercise the ML-KEM (ct_M) and X25519 (ct_X) components of the combined X-WING ciphertext. 

=== Response Example

[source, json]
----
  {
   "acvVersion": "1.0",  
   "vsId": "42",   
   "testGroups": [
     {
       "tgId": 2,
       "tests": [
         {
            "tcId": 26,
             "ss": "1D1AE..."
          }
        ]    
      }
     ]
   }
 
----







